//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.296
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionWebMVC.AdmPedidoWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pedido", Namespace="http://schemas.datacontract.org/2004/07/AppWS.Dominio")]
    [System.SerializableAttribute()]
    public partial class Pedido : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NPedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrioridadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaRegistro {
            get {
                return this.FechaRegistroField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaRegistroField, value) != true)) {
                    this.FechaRegistroField = value;
                    this.RaisePropertyChanged("FechaRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NPedido {
            get {
                return this.NPedidoField;
            }
            set {
                if ((this.NPedidoField.Equals(value) != true)) {
                    this.NPedidoField = value;
                    this.RaisePropertyChanged("NPedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prioridad {
            get {
                return this.PrioridadField;
            }
            set {
                if ((object.ReferenceEquals(this.PrioridadField, value) != true)) {
                    this.PrioridadField = value;
                    this.RaisePropertyChanged("Prioridad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pedido_det", Namespace="http://schemas.datacontract.org/2004/07/AppWS.Dominio")]
    [System.SerializableAttribute()]
    public partial class Pedido_det : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArticuloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoArticuloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NPedidoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Articulo {
            get {
                return this.ArticuloField;
            }
            set {
                if ((object.ReferenceEquals(this.ArticuloField, value) != true)) {
                    this.ArticuloField = value;
                    this.RaisePropertyChanged("Articulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoArticulo {
            get {
                return this.CodigoArticuloField;
            }
            set {
                if ((this.CodigoArticuloField.Equals(value) != true)) {
                    this.CodigoArticuloField = value;
                    this.RaisePropertyChanged("CodigoArticulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NPedido {
            get {
                return this.NPedidoField;
            }
            set {
                if ((this.NPedidoField.Equals(value) != true)) {
                    this.NPedidoField = value;
                    this.RaisePropertyChanged("NPedido");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdmPedidoWS.IAdmPedido")]
    public interface IAdmPedido {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmPedido/crear", ReplyAction="http://tempuri.org/IAdmPedido/crearResponse")]
        AplicacionWebMVC.AdmPedidoWS.Pedido crear(string usuario, string fecha, string prioridad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmPedido/listar", ReplyAction="http://tempuri.org/IAdmPedido/listarResponse")]
        AplicacionWebMVC.AdmPedidoWS.Pedido[] listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmPedido/creardet", ReplyAction="http://tempuri.org/IAdmPedido/creardetResponse")]
        AplicacionWebMVC.AdmPedidoWS.Pedido_det creardet(int npedido, int codarticulo, string articulo, int cantidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmPedido/listarDetalle", ReplyAction="http://tempuri.org/IAdmPedido/listarDetalleResponse")]
        AplicacionWebMVC.AdmPedidoWS.Pedido_det[] listarDetalle();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdmPedidoChannel : AplicacionWebMVC.AdmPedidoWS.IAdmPedido, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdmPedidoClient : System.ServiceModel.ClientBase<AplicacionWebMVC.AdmPedidoWS.IAdmPedido>, AplicacionWebMVC.AdmPedidoWS.IAdmPedido {
        
        public AdmPedidoClient() {
        }
        
        public AdmPedidoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdmPedidoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdmPedidoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdmPedidoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AplicacionWebMVC.AdmPedidoWS.Pedido crear(string usuario, string fecha, string prioridad) {
            return base.Channel.crear(usuario, fecha, prioridad);
        }
        
        public AplicacionWebMVC.AdmPedidoWS.Pedido[] listar() {
            return base.Channel.listar();
        }
        
        public AplicacionWebMVC.AdmPedidoWS.Pedido_det creardet(int npedido, int codarticulo, string articulo, int cantidad) {
            return base.Channel.creardet(npedido, codarticulo, articulo, cantidad);
        }
        
        public AplicacionWebMVC.AdmPedidoWS.Pedido_det[] listarDetalle() {
            return base.Channel.listarDetalle();
        }
    }
}
